#git clone https://github.com/tensorflow/tensorflow.git -b r1.13 ../../thirdparty/tensorflow/
rm -rf ../../thirdparty/tensorflow/tools/
rm -rf ../../thirdparty/tensorflow/third_party/
rm -rf ../../thirdparty/tensorflow/.git/
rm -rf ../../thirdparty/tensorflow/.github/
rm -rf ../../thirdparty/tensorflow/tensorflow/cc/
rm -rf ../../thirdparty/tensorflow/tensorflow/c/
rm -rf ../../thirdparty/tensorflow/tensorflow/core/
rm -rf ../../thirdparty/tensorflow/tensorflow/go/
rm -rf ../../thirdparty/tensorflow/tensorflow/java/
rm -rf ../../thirdparty/tensorflow/tensorflow/js/
rm -rf ../../thirdparty/tensorflow/tensorflow/examples/
rm -rf ../../thirdparty/tensorflow/tensorflow/compiler/
rm -rf ../../thirdparty/tensorflow/tensorflow/python/
rm -rf ../../thirdparty/tensorflow/tensorflow/tools/
rm -rf ../../thirdparty/tensorflow/tensorflow/contrib/
rm -rf ../../thirdparty/tensorflow/tensorflow/stream_executor/
rm -rf ../../thirdparty/tensorflow/tensorflow/g3doc/
rm -rf ../../thirdparty/tensorflow/tensorflow/docs_src/