#!/usr/bin/env python

Import('env')
Import('env_modules')

env_tensorflow = env_modules.Clone()
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/c/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/core/*.cc ")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/core/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/core/api/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/internal/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/optimized/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/reference/*.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/internal/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/internal/optimized/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/kernels/internal/reference/*.c")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/tools/make/downloads/farmhash/src/farmhash.cc")
env_tensorflow.add_source_files(env.modules_sources, "#thirdparty/tensorflow/lite/tools/make/downloads/fft2d/fftsg.c")
 
env_tensorflow.Append(CPPPATH=['#thirdparty/tensorflow'])
env_tensorflow.Append(CPPPATH=['#thirdparty/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include'])
if (not env.msvc):
    env_tensorflow.Append(CXXFLAGS="-std=c++11")

#env_tensorflow.Append(CPPFLAGS=['-DTF_LITE_STATIC_MEMORY'])

# Godot's own source files
env_tensorflow.add_source_files(env.modules_sources, "*.cpp")
